### ISSUE TITLE
Test Roadmap

### ISSUE THREAD

**Issue by aluzzardi** [docker/docker-e2e#75]
This is an attempt to summarize the overall effort and roadmap.

Eventually this will link to individual issues and will be mapped to an owner. Feel free to edit.

* Infrastructure
  * [ ] Build docker packages for every PR/master
  * [ ] Test definition format (per-repo configuration)
  * [ ] Platform matrix support
  * [ ] Jenkins integration
  * [ ] Define & Maintain base OS images
  * [ ] Switch to InfraKit
  * [ ] Windows support
  * [ ] P&Z support
* Tests
  * [ ] Upgrade tests (https://github.com/docker/docker/issues/32603#issuecomment-294388423): Install a release, run tests, upgrade, run tests
    * Should run upgrade from latest stable to master on every PR
    * Should run permutations of all supported version (e.g. 17.03 -> 17.12)
  * [ ] Stress: Continuously run tests on a long running cluster
  * [ ] Run tests (even new ones) on all supported Docker versions
  * [ ] docker/docker: extract tests so they can run on an already deployed engine
  * [ ] docker/docker: Run tests in a testkit environment
  * [ ] Add e2e Networking tests
  * [ ] Add e2e Swarm tests
  * [ ] Run all docker e2e tests on UCP & DTR

/cc @dhiltgen @chungers @vdemeester @nwt @RobbKistler

**Comment by aluzzardi** [comment]
@vdemeester 👍

**Comment by dhiltgen** [comment]
I believe we can consider windows support ~done at this point, on the machine branch.  Downstream projects are actively using it for testing mixed windows/linux clusters.

**Comment by AkihiroSuda** [comment]
- network partition
- packet ordering
- disk fault injection
